# Generated by Django 4.2.3 on 2023-07-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo_de_profil',
            field=models.ImageField(blank=True, null=True, upload_to='images/utilisateurs'),
        ),
    ]
