# Generated by Django 4.2.3 on 2023-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_utilisateur_photo_de_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='CNE_ou_code_massar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_apogee',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
