# Generated by Django 4.2.3 on 2023-07-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(blank=True, max_length=1000, null=True)),
                ('fichier_audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/messagerie')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/messagerie')),
                ('date_heure_de_creation', models.DateTimeField()),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repondu_par', to='messagerie.message')),
            ],
        ),
    ]
