# Generated by Django 4.2.3 on 2023-07-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0004_remove_message_document_remove_message_fichier_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recu',
        ),
    ]
