# Generated by Django 4.2.3 on 2023-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0005_remove_message_recu'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visible_pour_destinataire',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='visible_pour_expediteur',
            field=models.BooleanField(default=True),
        ),
    ]
