# Generated by Django 4.2.3 on 2023-07-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_commentaire_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='utilisateur',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='utilisateur',
            new_name='auteur',
        ),
    ]
