# Generated by Django 4.2.3 on 2023-07-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_commentaire_auteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.TextField(max_length=50),
        ),
    ]
