# Generated by Django 4.2.3 on 2023-07-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='filiere',
            field=models.CharField(blank=True, choices=[('IID', 'Informatique Et Ingenieurie Des Donnees'), ('IRIC', 'Ingenieurie Des Reseaux Intelligents Et Cybersecurite'), ('GPEE', 'Genie Des Procedees Energie Environnement'), ('GI', 'Genie Informatique'), ('GE', 'Genie Electrique')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='niveau',
            field=models.CharField(blank=True, choices=[('1', 'Premiere Annee'), ('2', 'Deuxieme Annee'), ('3', 'Troisieme Annee'), ('4', 'Quatrieme Annee'), ('5', 'Cinquieme Annee'), ('D', 'Doctorant')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_de_profil',
            field=models.ImageField(blank=True, null=True, upload_to='fichiers/images/utilisateurs'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('EL', 'Eleve'), ('AE', 'Ancien Eleve'), ('P', 'Professeur'), ('EN', 'Entreprise'), ('A', 'Administration'), ('AU', 'Autre')], max_length=2),
        ),
    ]
