# Generated by Django 4.2.3 on 2023-07-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_heure_de_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
